import Head from "next/head";
import { useEffect, useState } from "react";
import { Flex, Spinner, Text, Image, Button } from "@chakra-ui/react";
import { useRouter } from "next/router";
import {
  osName,
} from "react-device-detect";

export default function OverView() {
  const router = useRouter();
  const [showLinks, setShowLinks] = useState(false);

  useEffect(() => {
    (async () => {
      // 'itms://podcasts.apple.com/gh/podcast/pastor-oti-audio-podcasts/id1218400764?i=1000603333671' - Apple podcast
      // 'googlepodcasts://podcasts.google.com/feed/aHR0cHM6Ly9wYXN0b3JvdGkub3JnL2F1ZGlvcG9kY2FzdC9mZWVkL3BvZGNhc3Q' - Google podcast
      // 'https://podcasts.apple.com/gh/podcast/pastor-oti-audio-podcasts/id1218400764?i=1000603333671' - Apple podcast URL
      // 'https://podcasts.google.com/feed/aHR0cHM6Ly9wYXN0b3JvdGkub3JnL2F1ZGlvcG9kY2FzdC9mZWVkL3BvZGNhc3Q?sa=X&ved=2ahUKEwiQg8DqsPn9AhXYmycCHXrhDg8Q9sEGegQIARAI' - Google podcast URL

      try {
        switch (osName.toUpperCase()) {
          case "MAC OS":
            router.push(
              "itms://podcasts.apple.com/gh/podcast/pastor-oti-audio-podcasts/id1218400764"
            );
            break;
          case "IOS":
            router.push(
              "itms://podcasts.apple.com/gh/podcast/pastor-oti-audio-podcasts/id1218400764"
            );
            break;
          case "ANDROID":
            router.push(
              "googlepodcasts://podcasts.google.com/feed/aHR0cHM6Ly9wYXN0b3JvdGkub3JnL2F1ZGlvcG9kY2FzdC9mZWVkL3BvZGNhc3Q"
            );
            break;
          default:
            router.push(
              "https://podcasts.google.com/feed/aHR0cHM6Ly9wYXN0b3JvdGkub3JnL2F1ZGlvcG9kY2FzdC9mZWVkL3BvZGNhc3Q?sa=X&ved=2ahUKEwiQg8DqsPn9AhXYmycCHXrhDg8Q9sEGegQIARAI"
            );
            break;
        }
        //    throw new Error("lemons");
      } catch (error) {
        router.push(
          "https://podcasts.google.com/feed/aHR0cHM6Ly9wYXN0b3JvdGkub3JnL2F1ZGlvcG9kY2FzdC9mZWVkL3BvZGNhc3Q?sa=X&ved=2ahUKEwiQg8DqsPn9AhXYmycCHXrhDg8Q9sEGegQIARAI"
        );
      }
    })();

    start();
  }, []);

  const start = () => {
    setTimeout(() => {
      setShowLinks(true);
    }, 5000);
  };
  

  return (
    <>
      <Head>
        <title>Love Economy Church | Swollen Sunday - admin </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{backgroundColor:'#121846'}}>
        <Flex
          w="100%"
          height={"100vh"}
          mt={-50}
          justify={showLinks ? "flex-start" : "center"}
          align="center"
          direction={"column"}
          backgroundColor={'#121846'}
        >
          {showLinks ? (
            <>
              <Image src="/logo-white.png" alt="LEC Logo" w={24} mt={20} />
              <Text fontSize={30} fontWeight="bold" lineHeight={9} mt={5} color="white">
                Listen to Bishop Isaac
                <br />
                Oti-Boateng on podcast!
              </Text>
            <Flex justify={'space-between'} direction={'column'} gap={5} mt={5}>
                
              <Image  backgroundColor={'white'} borderRadius={10} onClick={()=>{
                router.push(
                    "https://podcasts.apple.com/gh/podcast/pastor-oti-audio-podcasts/id1218400764"
                  );
              }} padding={2} src="/apple-podcast.png" alt="podcast logo" w={80}  mt={20} cursor='pointer'/>
              
              <Image backgroundColor={'white'} borderRadius={10} onClick={()=>{
                 router.push(
                    "https://podcasts.google.com/feed/aHR0cHM6Ly9wYXN0b3JvdGkub3JnL2F1ZGlvcG9kY2FzdC9mZWVkL3BvZGNhc3Q?sa=X&ved=2ahUKEwiQg8DqsPn9AhXYmycCHXrhDg8Q9sEGegQIARAI"
                  );
              }} padding={2} src="/google podcast.png" alt="podcast logo" w={80}  mt={20}  cursor='pointer'/>


              </Flex>
            </>
          ) : (
            <>
              <Spinner size={"xl"} color="white"/>
              <Text mt={5} color="white">Redirecting...</Text>
            </>
          )}
        </Flex>
      </main>
    </>
  );
}
